indicators:
  - key: "CHW_001"
    description: "Total U5 children"
    indicatorQuery: "select count(distinct baseEntityId) from event ev inner join ec_child ch where ev.eventType = 'Child Registration' and ch.base_entity_id = ev.baseEntityId
    and ev.eventDate = '%s' and ev.baseEntityId
     in (select distinct ec_child.base_entity_id from ec_child where ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '') and date(ch.dob) > date('now', '-60 month')"

  - key: "CHW_002"
    description: "Children (0-11 months) who died in the last year"
    indicatorQuery: "select count(distinct event.baseEntityId) from event where eventType = 'Remove Child Under 5'
    and eventDate = '%s'
      and event.baseEntityId in (select ec_child.base_entity_id
      from ec_child where date(ec_child.dob) >= date('now', '-11 month') and date(ec_child.dod) >= date('now', '-12 month'))"

  - key: "CHW_003"
    description: "Children (12-59 months) who died in the last year"
    indicatorQuery: "select count(distinct event.baseEntityId) from event where eventType = 'Remove Child Under 5'
    and eventDate = '%s'
       and event.baseEntityId in (select ec_child.base_entity_id
       from ec_child where date(ec_child.dob) >= date('now', '-60 month') and date(ec_child.dob) < date('now', '-11 month') and date(ec_child.dod) >= date('now', '-12 month'))"

  - key: "CHW_004"
    description: "Children (0-59 months) with a birth certificate"
    indicatorQuery: "select count(distinct event.baseEntityId) from event where eventType = 'Birth Certification'
                         and eventDate = '%s'
                          and event.baseEntityId in (select distinct ec_child.base_entity_id from ec_child where ec_child.birth_cert = 'Yes'
                          and date(ec_child.dob) >= date('now', '-60 month') and ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '')"

  - key: "CHW_005"
    description: "Children (0-59 months) without a birth certificate"
    indicatorQuery: "select count(distinct event.baseEntityId) from event where eventType = 'Birth Certification'
                         and eventDate = '%s' and event.baseEntityId in (select distinct ec_child.base_entity_id from ec_child where ec_child.birth_cert = 'No'
                          and date(ec_child.dob) >= date('now', '-60 month') and ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '')"

  - key: "CHW_006"
    description: "Children (12-59 months) who were dewormed in the last 6 months"
    indicatorQuery: "select count(distinct ev.baseEntityId) from event ev inner join ec_child ec where ev.baseEntityId = ec.base_entity_id and date(ec.dob) > date('now', '-60 month') and date(ec.dob) <= date('now', '-11 month')
                     and ifnull(ec.dod,'') = '' and ifnull(ec.date_removed,'') = '' and ev.eventDate = '%s' and ev.eventType = 'Child Home Visit'
                     and ec.base_entity_id in (select home_visit_indicator_info.base_entity_id from home_visit_indicator_info where home_visit_indicator_info.service like 'Deworming%%' and home_visit_indicator_info.service_given = 1 and (date(home_visit_indicator_info.created_at >= date('now', '-6 month')) or date(home_visit_indicator_info.updated_at >= date('now', '-6 month'))))"

  - key: "CHW_007"
    description: "Children (12-59 months) who were not dewormed in the last 6 months"
    indicatorQuery: "select count(distinct ev.baseEntityId) from event ev inner join ec_child ec where ev.baseEntityId = ec.base_entity_id and date(ec.dob) > date('now', '-60 month') and date(ec.dob) <= date('now', '-11 month')
                     and ev.eventDate = '%s' and ev.eventType = 'Child Home Visit'
                     and ec.base_entity_id in (select home_visit_indicator_info.base_entity_id from home_visit_indicator_info where home_visit_indicator_info.service like 'Deworming%%'
                     and home_visit_indicator_info.service_given = 0 and (date(home_visit_indicator_info.created_at >= date('now', '-6 month')) or date(home_visit_indicator_info.updated_at >= date('now', '-6 month'))))"

  - key: "CHW_008"
    description: "Children (6-59 months) who received Vitamin A in the last 6 months"
    indicatorQuery: "select count(ev.baseEntityId) from event ev inner join ec_child ec where ev.baseEntityId = ec.base_entity_id and date(ec.dob) > date('now', '-60 month')
    and date(ec.dob) <= date('now', '-6 month') and ifnull(ec.dod,'') = '' and ifnull(ec.date_removed,'') = '' and ev.eventDate = '%s'
    and ev.eventType = 'Child Home Visit' and ec.base_entity_id in (select home_visit_indicator_info.base_entity_id from home_visit_indicator_info where home_visit_indicator_info.service like 'Vitamin A%%'
    and home_visit_indicator_info.service_given = 1 and (date(home_visit_indicator_info.created_at >= date('now', '-6 month'))
    or date(home_visit_indicator_info.updated_at >= date('now', '-6 month'))))"

  - key: "CHW_009"
    description: "Children (6-59 months) who did not receive Vitamin A in the last 6 months"
    indicatorQuery: "select count(ev.baseEntityId) from event ev inner join ec_child ec where ev.baseEntityId = ec.base_entity_id and date(ec.dob) > date('now', '-60 month')
    and date(ec.dob) <= date('now', '-6 month') and ifnull(ec.dod,'') = '' and ifnull(ec.date_removed,'') = '' and ev.eventDate = '%s' and ev.eventType = 'Child Home Visit'
                                       and ec.base_entity_id in (select home_visit_indicator_info.base_entity_id from home_visit_indicator_info where home_visit_indicator_info.service
                                       like 'Vitamin A%%' and home_visit_indicator_info.service_given = 0 and (date(home_visit_indicator_info.created_at >= date('now', '-6 month')) or date(home_visit_indicator_info.updated_at >= date('now', '-6 month'))))"

  - key: "CHW_010"
    description: "Children (0-5 months) exclusively breastfeeding in their most recent home visit"
    indicatorQuery: "select count(*)
                     from
                     (
                     select base_entity_id from home_visit_indicator_info
                     where home_visit_indicator_info.value = 'yes'and home_visit_indicator_info.service = 'Exclusive breastfeeding' group by base_entity_id
                     ) hi
                     inner join ec_child ec
                     on ec.base_entity_id = hi.base_entity_id
                     where date(ec.dob) > date('now', '-6 month')"

  - key: "CHW_011"
    description: "Children (0-5 months) not exclusively breastfeeding in their most recent home visit"
    indicatorQuery: "select count(*)
                 from
                 (
                 select base_entity_id from home_visit_indicator_info
                 where home_visit_indicator_info.value = 'no'and home_visit_indicator_info.service = 'Exclusive breastfeeding' group by base_entity_id
                 ) hi
                 inner join ec_child ec
                 on ec.base_entity_id = hi.base_entity_id
                 where date(ec.dob) > date('now', '-6 month')"


  - key: "CHW_012"
    description: "Children (6-23 months) up to date on MNP supplementation"
    indicatorQuery: "select count(distinct alerts.caseID) from alerts where alerts.scheduleName like 'MNP%%' and (alerts.status = 'upcoming' or alerts.status = 'normal')
      and alerts.caseID in (select ec_child.base_entity_id from ec_child where date(ec_child.dob) < date('now', '-6 month') and  date(ec_child.dob) > date('now', '-23 month')
      and ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '')"

  - key: "CHW_013"
    description: "Children (6-23 months) overdue for MNP supplementation"
    indicatorQuery: "select count(distinct alerts.caseID) from alerts where alerts.scheduleName like 'MNP%%' and alerts.status = 'urgent'
                           and alerts.caseID in (select ec_child.base_entity_id from ec_child where date(ec_child.dob) < date('now', '-6 month') and  date(ec_child.dob) > date('now', '-23 month')
                           and ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '')"

  - key: "CHW_014"
    description: "Children (0-23 months) up to date on immunizations"
    indicatorQuery: "select count(ec_child.base_entity_id) from ec_child where date(ec_child.dob) > date('now', '-24 month')
                                          and ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '' and ec_child.base_entity_id not in
                                          (select distinct alerts.caseID from alerts where (alerts.status = 'upcoming' or alerts.status = 'normal' or alerts.status = 'urgent') and alerts.scheduleName
                     					 in ('BCG','OPV 1', 'OPV 2', 'OPV 3', 'PCV 1', 'PCV 2', 'PCV 3', 'Penta 1', 'Penta 2', 'Penta 3', 'Rota 1', 'Rota 2', 'IPV', 'YF', 'MCV 1', 'MCV 2'))"

  - key: "CHW_015"
    description: "Children (0-23 months)  who are currently overdue for at least one or more vaccinations"
    indicatorQuery: "select count(ec_child.base_entity_id) from ec_child where date(ec_child.dob) > date('now', '-24 month')
                                          and ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '' and ec_child.base_entity_id in
                                          (select distinct alerts.caseID from alerts where alerts.status = 'urgent' and alerts.scheduleName
                     					 in ('BCG','OPV 1', 'OPV 2', 'OPV 3', 'PCV 1', 'PCV 2', 'PCV 3', 'Penta 1', 'Penta 2', 'Penta 3', 'Rota 1', 'Rota 2', 'IPV', 'YF', 'MCV 1', 'MCV 2'))"